package pojo;
// Generated Oct 13, 2022 10:57:47 PM by Hibernate Tools 4.3.1

import dao.Daologin;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TabelUser generated by hbm2java
 */
@ManagedBean
public class TabelUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;

    public TabelUser() {
    }

    public TabelUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String login_user(){
         Daologin uDao = new Daologin();
         List<TabelUser> us = uDao.getBy(username, password);
         try{
            if (us != null){
                username = us.get(0).username;
                password = us.get(0).password;
                return "viewdata.xhtml";
            }
        }catch (Exception e){
            System.out.print(e);
        }
        return "gagal.xhtml";
     }


}
    

